# Generated by Django 2.2.1 on 2019-10-07 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='paymaneth_method',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.Product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='inventory_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.Inventory'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
